{
 "title": "Agent Events",
 "tags": [ "ConnectAgentEvents" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "InstanceAlias",
    "label": "Instance",
    "query": "SELECT distinct  (\"InstanceAlias\")\nFROM \"$DatabaseName\".\"Instance\" "
   },
   { "name": "DatabaseName", "label": "Database Name", "query": "ConnectRealTime" },
   {
    "name": "AgentStatus",
    "label": "Agent Status",
    "query": "SELECT  distinct  CurrentAgentSnapshot_AgentStatus_Name FROM \"$DatabaseName\".\"AgentEvent\" "
   },
   { "name": "StatusType", "label": "Status Type", "query": "ROUTABLE, CUSTOM, OFFLINE" },
   {
    "name": "RoutingProfile",
    "label": "Routing Profile",
    "query": "SELECT  distinct  CurrentAgentSnapshot_Configuration_RoutingProfile_Name FROM \"$DatabaseName\".\"AgentEvent\" "
   },
   { "name": "OnContact", "label": "On Contact", "query": "OnContact,Not OnContact" }
  ]
 },
 "panels": [
  { "title": "Summary from Agent Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Summary",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Agents Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "With \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n),\nBaseQuery as (\n  SELECT \n    \"CurrentAgentSnapshot_Configuration_Username\", \n    \"CurrentAgentSnapshot_AgentStatus_Name\",   \n    \"CurrentAgentSnapshot_AgentStatus_Type\",   \n    \"_X_OnContact\",\n    \"CurrentAgentSnapshot_Configuration_RoutingProfile_Name\",\n    \"CurrentAgentSnapshot_AgentStatus_StartTimestamp\",\n    \"EventTimestamp\",\n    \"EventType\" \"Update Event\",\n    \"InstanceARN\",\n    \"_X_AvailableChatSlots\",\n    \"_X_AvailableVoiceSlots\",\n    \"_X_AvailableTaskSlots\", \n\n    ROW_NUMBER() OVER (PARTITION BY \"CurrentAgentSnapshot_Configuration_Username\" ORDER BY time desc) AS seqnum\n  FROM \"$DatabaseName\".\"AgentEvent\" eventsourcetable\n\n  WHERE \n    time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})  \n    AND \"measure_name\" = 'AgentEvent'\n)\nSelect \n  eventsource.\"CurrentAgentSnapshot_Configuration_Username\" \"Username\", \n  eventsource.\"CurrentAgentSnapshot_AgentStatus_Name\" \"Status\",   \n  CASE WHEN eventsource.\"_X_OnContact\" THEN 'OnContact'   ELSE 'Not OnContact' END \"Contact Status\",\n  eventsource.\"CurrentAgentSnapshot_AgentStatus_Type\" \"Type\",   \n  eventsource.\"CurrentAgentSnapshot_Configuration_RoutingProfile_Name\" \"Routing Profile\",\n  date_diff('second',  from_iso8601_timestamp(eventsource.\"CurrentAgentSnapshot_AgentStatus_StartTimestamp\"), now()) \"In Status Time\",    \n  from_iso8601_timestamp(eventsource.\"CurrentAgentSnapshot_AgentStatus_StartTimestamp\") \"Status Start\",\n  from_iso8601_timestamp(eventsource.\"EventTimestamp\") \"Last Updated\",\n  \"Update Event\", \n  eventsource.\"_X_AvailableChatSlots\" \"Available Chat Slots\", \n  eventsource.\"_X_AvailableVoiceSlots\" \"Available Voice Slots\",\n  eventsource.\"_X_AvailableTaskSlots\" \"Available Task Slots\", \n  'Agent' \"EntityType\"\n\nFROM BaseQuery eventsource\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsource.InstanceARN = instance.Arn\nWHERE seqnum=1\n    AND (\"CurrentAgentSnapshot_AgentStatus_Name\" IN ( $AgentStatus ))\n    AND (\"CurrentAgentSnapshot_AgentStatus_Type\" IN ( $StatusType ))\n    AND (\"CurrentAgentSnapshot_Configuration_RoutingProfile_Name\" IN ( $RoutingProfile  ))\n    AND (CASE WHEN _X_OnContact THEN 'OnContact'   ELSE 'Not OnContact' END IN ( $OnContact   ))\n    AND instance.InstanceAlias IN ( $InstanceAlias )\nORDER BY \"CurrentAgentSnapshot_Configuration_Username\"\n",
     "table": "\"AgentConfig\""
    }
   ]
  },
  {
   "title": "TimeSeries Analysis of Agent Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Agent Availability Through Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "With \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n), \nBaseAvailabilityByDate AS (\nSELECT \nBIN(time, greatest($__interval_ms,5m)) binned_timestamp,\nAgentARN,\nMax(CASE\n    WHEN CurrentAgentSnapshot_AgentStatus_Name = 'Available' THEN 1\n    ELSE 0\nEND) \"Max Availability\",\nMin(CASE\n    WHEN CurrentAgentSnapshot_AgentStatus_Name = 'Available' THEN 1\n    ELSE 0\nEND) \"Min Availability\"\nFROM \"$DatabaseName\".\"AgentEvent\" eventsource\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsource.InstanceARN = instance.Arn\nWhere \n    time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to}) \n    AND \"measure_name\" = 'AgentEvent' \n    AND instance.InstanceAlias IN ( $InstanceAlias )\nGroup by BIN(time, greatest($__interval_ms,5m)) , AgentARN\n),\nSumAvailabilityByDate AS (\nSELECT \nbinned_timestamp,\nsum (\"Max Availability\") as \"Max Number of Available Agents\",\nsum (\"Min Availability\") as \"Min Number of Available Agents\"\nFROM BaseAvailabilityByDate\nGROUP BY binned_timestamp\n)\nSELECT \nCREATE_TIME_SERIES (binned_timestamp,\"Max Number of Available Agents\") \"Max Number of Available Agents\",\nCREATE_TIME_SERIES (binned_timestamp,\"Min Number of Available Agents\") \"Min Number of Available Agents\"\nFROM SumAvailabilityByDate",
     "table": "\"AgentConfig\""
    }
   ]
  },
  {
   "title": "Available Slots Through Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 23 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "\nWith \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n),\n BaseAvailabilityByDate AS (\nSelect \nBIN(time, greatest($__interval_ms,5m)) binned_timestamp,\nAgentARN,\nMax(\"_X_AvailableChatSlots\") \"Max _X_AvailableChatSlots\",\nMin(\"_X_AvailableChatSlots\") \"Min _X_AvailableChatSlots\",\nMax(\"_X_AvailableVoiceSlots\") \"Max _X_AvailableVoiceSlots\",\nMin(\"_X_AvailableVoiceSlots\") \"Min _X_AvailableVoiceSlots\",\nMax(\"_X_AvailableTaskSlots\") \"Max _X_AvailableTaskSlots\",\nMin(\"_X_AvailableTaskSlots\") \"Min _X_AvailableTaskSlots\"\nFROM \"$DatabaseName\".\"AgentEvent\" eventsource\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsource.InstanceARN = instance.Arn\nWhere \n  time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})    \n  AND CurrentAgentSnapshot_AgentStatus_Name = 'Available'\n  AND \"measure_name\" = 'AgentEvent'\n   AND instance.InstanceAlias IN ( $InstanceAlias )\nGroup by BIN(time, greatest($__interval_ms,5m)), AgentARN\n),\nSumAvailabilityByTime as (SELECT\nbinned_timestamp,\nCOALESCE(Sum(\"Max _X_AvailableChatSlots\"),0) \"Max _X_AvailableChatSlots\",\nCOALESCE(Sum(\"Min _X_AvailableChatSlots\"),0) \"Min _X_AvailableChatSlots\",\nCOALESCE(Sum(\"Max _X_AvailableVoiceSlots\"),0) \"Max _X_AvailableVoiceSlots\",\nCOALESCE(Sum(\"Min _X_AvailableVoiceSlots\"),0) \"Min _X_AvailableVoiceSlots\",\nCOALESCE(Sum(\"Max _X_AvailableTaskSlots\"),0) \"Max _X_AvailableTaskSlots\",\nCOALESCE(Sum(\"Min _X_AvailableTaskSlots\"),0) \"Min _X_AvailableTaskSlots\"\nFROM BaseAvailabilityByDate\nGROUP BY binned_timestamp\n)\nSELECT \nCREATE_TIME_SERIES (binned_timestamp,\"Max _X_AvailableChatSlots\") \"Max AvailableChatSlots\",\nCREATE_TIME_SERIES (binned_timestamp,\"Min _X_AvailableChatSlots\") \"Min AvailableChatSlots\",\nCREATE_TIME_SERIES (binned_timestamp,\"Max _X_AvailableVoiceSlots\") \"Max AvailableVoiceSlots\",\nCREATE_TIME_SERIES (binned_timestamp,\"Min _X_AvailableVoiceSlots\") \"Min AvailableVoiceSlots\",\nCREATE_TIME_SERIES (binned_timestamp,\"Max _X_AvailableTaskSlots\") \"Max AvailableTaskSlots\",\nCREATE_TIME_SERIES (binned_timestamp,\"Min _X_AvailableTaskSlots\") \"Min AvailableTaskSlots\"\nFROM SumAvailabilityByTime",
     "table": "\"AgentConfig\""
    }
   ]
  },
  {
   "title": "Contact Metrics from Agent Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Missed Contacts Leaderboard",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "\nWith \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n), \nUserBaseQuery AS (\n    SELECT Username,\"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"User\" \n    GROUP BY time, Username, \"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn\n),\nUserNameQuery AS (\n    SELECT Username, \"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn FROM UserBaseQuery\n    WHERE seqnum =1\n), \nBaseQuery AS (\nSELECT \n  eventsourcetable.\"Agent_AgentARN\",\n  Count (distinct eventsourcetable.\"ContactId\") \"# of Contacts\"\nFROM \"$DatabaseName\".\"AgentEvent_Contact\" eventsourcetable\nWHERE \n   eventsourcetable.time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})    \n   AND eventsourcetable.\"State\" = 'MISSED'\nGROUP BY eventsourcetable.\"Agent_AgentARN\"\nORDER BY \"# of Contacts\" DESC\nLIMIT 5\n)\nSELECT \n  users.\"Username\",\n  users.\"IdentityInfo_FirstName\" \"First Name\",\n  users.\"IdentityInfo_LastName\" \"Last Name\",\n  eventsourcetable.\"# of Contacts\"\nFROM BaseQuery eventsourcetable\n    LEFT JOIN UserNameQuery users\n    ON users.Arn = eventsourcetable.Agent_AgentARN\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsourcetable.Agent_AgentARN like concat(instance.Arn,'%')\n",
     "table": "\"AgentConfig\""
    }
   ]
  },
  {
   "title": "Answered Contacts Leaderboard",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 34 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "With \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n), \nUserBaseQuery AS (\n    SELECT Username,\"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"User\" \n    GROUP BY time, Username, \"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn\n),\nUserNameQuery AS (\n    SELECT Username, \"IdentityInfo_FirstName\",\"IdentityInfo_LastName\", Arn FROM UserBaseQuery\n    WHERE seqnum =1\n), \nBaseQuery AS (\nSELECT \n  eventsourcetable.\"Agent_AgentARN\", \n  Count (distinct eventsourcetable.\"ContactId\") \"# of Contacts\"\nFROM \"$DatabaseName\".\"AgentEvent_Contact\" eventsourcetable\nWHERE \n  eventsourcetable.\"State\" = 'CONNECTED'\n  AND eventsourcetable.time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})    \nGROUP BY eventsourcetable.\"Agent_AgentARN\"\nORDER BY \"# of Contacts\" DESC\nLIMIT 5\n)\nSELECT \n  users.\"Username\",\n  users.\"IdentityInfo_FirstName\" \"First Name\",\n  users.\"IdentityInfo_LastName\" \"Last Name\",\n  eventsourcetable.\"# of Contacts\"\nFROM BaseQuery eventsourcetable\n    LEFT JOIN UserNameQuery users\n    ON users.Arn = eventsourcetable.Agent_AgentARN\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsourcetable.Agent_AgentARN like concat(instance.Arn,'%')",
     "table": "\"AgentConfig\""
    }
   ]
  },
  {
   "title": "Missed Contacts per Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 34 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "measure_name",
     "rawQuery": "With \nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n)\nSELECT \n  \"Queue_Name\",\n  Count (distinct \"ContactId\") \"# of Contacts\"\nFROM \"$DatabaseName\".\"AgentEvent_Contact\" eventsourcetable\n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsourcetable.Agent_AgentARN like concat(instance.Arn,'%')\nWHERE \n  \"State\" = 'MISSED'\n  AND time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})  \nGROUP BY \"Queue_Name\"\nORDER BY \"# of Contacts\"  DESC\n",
     "table": "\"AgentConfig\""
    }
   ]
  }
 ]
}