{
 "title": "Contact Events",
 "tags": [ "ConnectContactEvents" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "InstanceAlias",
    "label": "Instance",
    "query": "SELECT distinct  (\"InstanceAlias\")\nFROM \"$DatabaseName\".\"Instance\" "
   },
   { "name": "DatabaseName", "label": "DatabaseName", "query": "ConnectRealTime" },
   { "name": "Channel", "label": "Channel Name", "query": "VOICE, CHAT, TASK" },
   {
    "name": "InitiationMethod",
    "label": "Initiation Method",
    "query": "INBOUND,\nOUTBOUND,\nTRANSFER,\nCALLBACK,\nAPI,\nQUEUE_TRANSFER,\nEXTERNAL_OUTBOUND,\nMONITOR,\nDISCONNECT"
   },
   {
    "name": "Status",
    "label": "Status",
    "query": "INITIATED,\nCONNECTED_TO_SYSTEM,\nQUEUED,\nCONNECTED_TO_AGENT,\nDISCONNECTED,\nHUMAN_ANSWERED,\nVOICEMAIL_BEEP,\nVOICEMAIL_NO_BEEP,\nAMD_UNANSWERED,\nAMD_UNRESOLVED,\nSIT_TONE_BUSY,\nSIT_TONE_INVALID_NUMBER,\nSIT_TONE_DETECTED,\nFAX_MACHINE_DETECTED,\nAMD_ERROR"
   },
   {
    "name": "QueueName",
    "label": "Queue Name",
    "query": "SELECT distinct  (\"Name\")\nFROM \"$DatabaseName\".\"Queue\",\"$DatabaseName\".\"Instance\"  \nWhere \"Queue\".\"QueueArn\" like Concat(\"Instance\".\"Arn\", '%') \nAND \"Instance\".\"InstanceAlias\" IN (${InstanceAlias:sqlstring})\nUNION \nSelect '<None>'"
   },
   { "name": "SLATresholdSecs", "label": "SLA Treshold Secs", "query": "20" },
   { "name": "SLAMinQueueSecs", "label": "Queue short abandon (Secs)", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Summary from Contact Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Contacts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "With Agent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "In Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Avg. Abandon Time ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Contact Count per channel",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Contact Count per Current Status ",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Contact Count per Initiation Method",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Not Queued ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Abandon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Handled",
   "type": "stat",
   "description": "Answered, Disconnected / Completed",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Avg Speed of Answer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Service Level",
   "type": "stat",
   "description": "Calls answered within SLA / (Calls answered + Calls long abandoned)",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "In Queue Not Passed SLA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Answered Within SLA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Short Abandon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Waiting in Queue",
   "type": "table",
   "description": "Queues only appear if they have any contacts currently in Queue",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Queue Service Levels",
   "type": "table",
   "description": "Queues do appear if their SLA is 0. Each Queue need at least one contact within the Service Level to be in the list.   ",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "In Queue Passed SLA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Not Answered Within SLA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Long Abandon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Contacts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawQuery": "WITH \nQueueBaseQuery AS (\n    SELECT Name, QueueArn, ROW_NUMBER() OVER (PARTITION BY \"QueueArn\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"Queue\" \n    GROUP BY time, Name, QueueArn\n),\nQueueNameQuery AS (\n    SELECT Name, QueueArn FROM QueueBaseQuery\n    WHERE seqnum =1\n),\nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n),\nBaseContactQuery AS (\n    SELECT \n        time, \n        contactId , \n        channel ,\n        queueInfo_queueArn, \n        eventType,\n        initiationMethod,\n        queueInfo_enqueueTimestamp,\n        previousContactId,\n        disconnectTimestamp,\n        instanceArn,\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.disconnectTimestamp)) \"Queue To Disconnect Secs\",\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.agentInfo_connectedToAgentTimestamp)) \"Queue To Answer Secs\" ,\n\n            ROW_NUMBER() OVER (PARTITION BY \"contactId\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"ContactEvent\" eventsourcetable\n    WHERE \n        time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})  \n        AND \"measure_name\" = 'ContactEvent'\n        AND \"channel\" IN ($Channel)\n        AND \"initiationMethod\" IN ($InitiationMethod)\n),\nContactQuery AS (\nSELECT \n    eventsource.time \"Time\",\n    eventsource.contactId \"Contact Id\", \n    eventsource.channel \"Channel\",\n    queuenames.Name \"Queue Name\", \n   \tinstance.InstanceAlias \"Instance Alias\",\n   eventsource.eventType \"Status\",\n    eventsource.initiationMethod \"Initiation Method\",\n    CASE\n        WHEN (  eventsource.\"Queue To Answer Secs\" IS NOT NULL )\n            THEN eventsource.\"Queue To Answer Secs\"\n        ELSE \n            eventsource.\"Queue To Disconnect Secs\"\n    END  \"Queue Wait Secs\",  \n    eventsource.\"Queue To Answer Secs\" \"Queue To Answer Secs\",\n    eventsource.\"Queue To Disconnect Secs\" \"Queue To Disconnect Secs\",\n    CASE\n        WHEN (  eventsource.eventType = 'QUEUED' )\n            THEN date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())\n        ELSE NULL\n    END \"Current Queue Seconds\" , \n    CASE\n        WHEN (  eventsource.queueInfo_queueArn is NULL )\n            THEN false\n        ELSE true\n    END \"Queued\" ,    \n\n\n    eventsource.previousContactId \"Previous Contact Id\",\n\n    CASE\n        WHEN (  eventsource.initiationMethod IN ('CALLBACK') )\n            THEN 'FOLLOWER'\n        WHEN (  nextContact.channel <> 'TASK' AND nextContact.initiationMethod IS NOT NULL )\n            THEN 'FOLLOWED'\n        WHEN (  eventsource.queueInfo_queueArn IS NULL )\n            THEN 'NOT QUEUED'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())>=$SLATresholdSecs))\n            THEN 'QUEUED AND PASSED SLA'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now()) < $SLATresholdSecs))\n            THEN 'QUEUED AND NOT PASSED SLA'\n        WHEN  (eventsource.\"Queue To Answer Secs\" IS NULL ) AND (eventsource.\"Queue To Disconnect Secs\" >= 0 ) AND (eventsource.\"Queue To Disconnect Secs\" < $SLAMinQueueSecs ) -- Abondened before waiting min wait time  \n            THEN 'SHORT ABANDONED'\n        WHEN  (eventsource.\"Queue To Answer Secs\" IS NULL ) AND (eventsource.\"Queue To Disconnect Secs\" >= $SLAMinQueueSecs )  \n            THEN 'LONG ABANDONED'\n        WHEN  (eventsource.\"Queue To Answer Secs\" >= $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED NOT WITHIN SLA'\n        WHEN  (eventsource.\"Queue To Answer Secs\" < $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED WITHIN SLA'\n        ELSE 'UNCATEGORIZED'\n    END \"SLAStatus\" ,\n    nextContact.initiationMethod \"Follower Method\",\n    'Contact' \"Entity Type\"\nFROM BaseContactQuery eventsource \n    LEFT JOIN QueueNameQuery queuenames\n    ON eventsource.queueInfo_queueArn = queuenames.QueueArn\n    LEFT JOIN BaseContactQuery nextContact\n    ON eventsource.contactId = nextContact.previousContactId AND nextContact.seqnum =1  AND nextContact.channel<>'TASK'\n\tLEFT JOIN InstanceAliasQuery instance\n    ON eventsource.instanceArn = instance.Arn\nWHERE \n    eventsource.seqnum =1 \n    AND  COALESCE(queuenames.Name,'<None>')  IN ($QueueName) \n    AND instance.InstanceAlias IN ($InstanceAlias)\n    AND eventsource.eventType IN ($Status)\nORDER BY eventsource.time DESC\n) \n\nSelect cq.*, \n    (select count (distinct (\"Contact Id\")) from ContactQuery  ) \"Total Records\" , \n        CASE\n        WHEN ( cq.\"SLAStatus\" IN ('ANSWERED WITHIN SLA') )\n            THEN true\n        WHEN ( cq.\"SLAStatus\" IN ('LONG ABANDONED','ANSWERED NOT WITHIN SLA') ) -- 'QUEUED AND PASSED SLA', can be added for queued items \n            THEN false\n        ELSE NULL\n    END \"Within SLA\",\n    (select count (distinct (\"Contact Id\")) from ContactQuery icq \n        Where icq.\"SLAStatus\" IN ('LONG ABANDONED','ANSWERED NOT WITHIN SLA','ANSWERED WITHIN SLA') -- 'QUEUED AND PASSED SLA', can be added for queued items \n    ) \"Total Records For SLA\" , \n    (select count (distinct (\"Contact Id\")) from ContactQuery icq \n        Where icq.\"Queue Name\" = cq.\"Queue Name\" and icq.\"SLAStatus\" IN ('LONG ABANDONED','ANSWERED NOT WITHIN SLA','ANSWERED WITHIN SLA')  -- 'QUEUED AND PASSED SLA', can be added for queued items \n    ) \"Total Records in Queue For SLA\"\nfrom ContactQuery cq\nORDER BY  cq.\"Time\" DESC\n\n\n\n"
    }
   ]
  },
  {
   "title": "TimeSeries Analysis of Contact Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Contact Status Timeseries Analysis",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "statusname",
     "rawQuery": "WITH \nQueueBaseQuery AS (\n    SELECT Name, QueueArn, ROW_NUMBER() OVER (PARTITION BY \"QueueArn\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"Queue\" \n    GROUP BY time, Name, QueueArn\n),\nQueueNameQuery AS (\n    SELECT Name, QueueArn FROM QueueBaseQuery\n    WHERE seqnum =1\n),\nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n),\nBaseContactQuery AS (\n    SELECT \n        time, \n        contactId , \n        channel ,\n        queueInfo_queueArn, \n        eventType,\n        initiationMethod,\n        queueInfo_enqueueTimestamp,\n        previousContactId,\n        disconnectTimestamp,       \n        instanceArn,\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.disconnectTimestamp)) \"Queue Abandon Secs\",\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.agentInfo_connectedToAgentTimestamp)) \"Queue Answer Secs\" ,\n\n            ROW_NUMBER() OVER (PARTITION BY \"contactId\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"ContactEvent\" eventsourcetable\n    WHERE \n        time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})  \n        AND \"measure_name\" = 'ContactEvent'\n        AND \"channel\" IN ($Channel)\n        AND \"initiationMethod\" IN ($InitiationMethod)\n),\nContactQuery AS (\nSELECT \n    eventsource.time ,\n    eventsource.contactId \"Contact Id\", \n    eventsource.channel \"Channel\",\n    queuenames.Name \"Queue Name\", \n    instance.InstanceAlias \"Instance Alias\",\n    eventsource.eventType \"Status\",\n    eventsource.initiationMethod \"Initiation Method\",\n    eventsource.\"Queue Answer Secs\" \"Queue Answer Secs\",\n    eventsource.\"Queue Abandon Secs\" \"Queue Abandon Secs\",\n    CASE\n        WHEN (  eventsource.eventType = 'QUEUED' )\n            THEN date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())\n        ELSE NULL\n    END \"Current Queue Seconds\" , \n    CASE\n        WHEN (  eventsource.queueInfo_queueArn is NULL )\n            THEN false\n        ELSE true\n    END \"Queued\" ,    \n\n\n    eventsource.previousContactId \"Previous Contact Id\",\n\n    CASE\n        WHEN (  eventsource.initiationMethod IN ('CALLBACK') )\n            THEN 'FOLLOWER'\n        WHEN (  nextContact.initiationMethod IS NOT NULL )\n            THEN 'FOLLOWED'\n        WHEN (  eventsource.queueInfo_queueArn IS NULL )\n            THEN 'NOT QUEUED'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())>=$SLATresholdSecs))\n            THEN 'QUEUED AND PASSED SLA'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now()) < $SLATresholdSecs))\n            THEN 'QUEUED AND NOT PASSED SLA'\n        WHEN  (eventsource.\"Queue Answer Secs\" IS NULL ) AND (eventsource.\"Queue Abandon Secs\" > 0 ) AND (eventsource.\"Queue Abandon Secs\" < $SLAMinQueueSecs ) -- Abondened before waiting min wait time  \n            THEN 'SHORT ABANDONED'\n        WHEN  (eventsource.\"Queue Answer Secs\" IS NULL ) AND (eventsource.\"Queue Abandon Secs\" >= $SLAMinQueueSecs )  \n            THEN 'LONG ABANDONED'\n        WHEN  (eventsource.\"Queue Answer Secs\" >= $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED NOT WITHIN SLA'\n        WHEN  (eventsource.\"Queue Answer Secs\" < $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED WITHIN SLA'\n        ELSE 'UNCATEGORIZED'\n    END \"SLAStatus\" ,\n    nextContact.initiationMethod \"Follower Method\",\n    'Contact' \"Entity Type\"\nFROM BaseContactQuery eventsource \n    LEFT JOIN QueueNameQuery queuenames\n    ON eventsource.queueInfo_queueArn = queuenames.QueueArn\n    LEFT JOIN BaseContactQuery nextContact\n    ON eventsource.contactId = nextContact.previousContactId AND nextContact.seqnum =1  \n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsource.instanceArn = instance.Arn\n\nWHERE \n     COALESCE(queuenames.Name,'<None>')  IN ($QueueName) \n    AND instance.InstanceAlias IN ($InstanceAlias)\n    AND eventsource.eventType IN ($Status)\nORDER BY eventsource.time DESC\n) ,\n\n\n\n\n\n\nBaseBinning AS (\nSELECT \n\tBIN(time, greatest($__interval_ms,5m)) binned_timestamp,\n    \"Contact Id\",\n    \"Status\"\nFROM ContactQuery eventsourcetable\nWHERE \n    COALESCE(\"Queue Name\",'<None>')  IN ($QueueName) \nGroup by BIN(time, greatest($__interval_ms,5m)),  \"Contact Id\",\"Status\"\n),\n\nCountUsersInBins AS (\nSELECT \n\tbinned_timestamp,\n   \"Status\",\n\tcount (distinct \"Contact Id\") \"Number of Contacts\"\nFROM BaseBinning\nGROUP BY binned_timestamp, \"Status\"\n)\n\nSELECT \n\"Status\", CREATE_TIME_SERIES (binned_timestamp,\"Number of Contacts\") \"Num of\"\nFROM CountUsersInBins\nGROUP by \"Status\"\nORDER By \"Status\"\n\n\n\n",
     "table": "\"Table1\""
    }
   ]
  },
  {
   "title": "Service Level Metrics Count Timeseries Analysis",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "database": "\"test\"",
     "measure": "statusname",
     "rawQuery": "WITH \nQueueBaseQuery AS (\n    SELECT Name, QueueArn, ROW_NUMBER() OVER (PARTITION BY \"QueueArn\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"Queue\" \n    GROUP BY time, Name, QueueArn\n),\nQueueNameQuery AS (\n    SELECT Name, QueueArn FROM QueueBaseQuery\n    WHERE seqnum =1\n),\nInstanceBaseQuery AS (\n    SELECT InstanceAlias, Arn, ROW_NUMBER() OVER (PARTITION BY \"Arn\" ORDER BY time desc) AS seqnum \n    FROM \"ConnectRealTime\".\"Instance\" \n    GROUP BY time, InstanceAlias, Arn\n),\nInstanceAliasQuery AS (\n    SELECT InstanceAlias, Arn FROM InstanceBaseQuery\n    WHERE seqnum =1\n),\nBaseContactQuery AS (\n    SELECT \n        time, \n        contactId , \n        channel ,\n        queueInfo_queueArn, \n        eventType,\n        initiationMethod,\n        queueInfo_enqueueTimestamp,\n        previousContactId,\n        disconnectTimestamp,       \n        instanceArn,\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.disconnectTimestamp)) \"Queue Abandon Secs\",\n        date_diff('second',  from_iso8601_timestamp(eventsourcetable.queueInfo_enqueueTimestamp), from_iso8601_timestamp(eventsourcetable.agentInfo_connectedToAgentTimestamp)) \"Queue Answer Secs\" ,\n\n            ROW_NUMBER() OVER (PARTITION BY \"contactId\" ORDER BY time desc) AS seqnum \n    FROM \"$DatabaseName\".\"ContactEvent\" eventsourcetable\n    WHERE \n        time BETWEEN from_milliseconds(${__from}) AND from_milliseconds(${__to})  \n        AND \"measure_name\" = 'ContactEvent'\n        AND \"channel\" IN ($Channel)\n        AND \"initiationMethod\" IN ($InitiationMethod)\n),\nContactQuery AS (\nSELECT \n    eventsource.time ,\n    eventsource.contactId \"Contact Id\", \n    eventsource.channel \"Channel\",\n    queuenames.Name \"Queue Name\", \n    instance.InstanceAlias \"Instance Alias\",\n    eventsource.eventType \"Status\",\n    eventsource.initiationMethod \"Initiation Method\",\n    eventsource.\"Queue Answer Secs\" \"Queue Answer Secs\",\n    eventsource.\"Queue Abandon Secs\" \"Queue Abandon Secs\",\n    CASE\n        WHEN (  eventsource.eventType = 'QUEUED' )\n            THEN date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())\n        ELSE NULL\n    END \"Current Queue Seconds\" , \n    CASE\n        WHEN (  eventsource.queueInfo_queueArn is NULL )\n            THEN false\n        ELSE true\n    END \"Queued\" ,    \n\n\n    eventsource.previousContactId \"Previous Contact Id\",\n\n    CASE\n        WHEN (  eventsource.initiationMethod IN ('CALLBACK') )\n            THEN 'FOLLOWER'\n        WHEN (  nextContact.initiationMethod IS NOT NULL )\n            THEN 'FOLLOWED'\n        WHEN (  eventsource.queueInfo_queueArn IS NULL )\n            THEN 'NOT QUEUED'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now())>=$SLATresholdSecs))\n            THEN 'QUEUED AND PASSED SLA'\n        WHEN (  eventsource.eventType = 'QUEUED'  AND  (date_diff('second',  from_iso8601_timestamp(eventsource.queueInfo_enqueueTimestamp), now()) < $SLATresholdSecs))\n            THEN 'QUEUED AND NOT PASSED SLA'\n        WHEN  (eventsource.\"Queue Answer Secs\" IS NULL ) AND (eventsource.\"Queue Abandon Secs\" > 0 ) AND (eventsource.\"Queue Abandon Secs\" < $SLAMinQueueSecs ) -- Abondened before waiting min wait time  \n            THEN 'SHORT ABANDONED'\n        WHEN  (eventsource.\"Queue Answer Secs\" IS NULL ) AND (eventsource.\"Queue Abandon Secs\" >= $SLAMinQueueSecs )  \n            THEN 'LONG ABANDONED'\n        WHEN  (eventsource.\"Queue Answer Secs\" >= $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED NOT WITHIN SLA'\n        WHEN  (eventsource.\"Queue Answer Secs\" < $SLATresholdSecs ) -- Answered before treshold \n            THEN 'ANSWERED WITHIN SLA'\n        ELSE 'UNCATEGORIZED'\n    END \"SLAStatus\" ,\n    nextContact.initiationMethod \"Follower Method\",\n    'Contact' \"Entity Type\"\nFROM BaseContactQuery eventsource \n    LEFT JOIN QueueNameQuery queuenames\n    ON eventsource.queueInfo_queueArn = queuenames.QueueArn\n    LEFT JOIN BaseContactQuery nextContact\n    ON eventsource.contactId = nextContact.previousContactId AND nextContact.seqnum =1  \n    LEFT JOIN InstanceAliasQuery instance\n    ON eventsource.instanceArn = instance.Arn\nWHERE \n     COALESCE(queuenames.Name,'<None>')  IN ($QueueName) \n    AND eventsource.eventType IN ($Status)\n    AND instance.InstanceAlias IN ($InstanceAlias)\nORDER BY eventsource.time DESC\n) ,\n\n\n\n\n\nBaseBinning AS (\nSELECT \n    BIN(time, greatest($__interval_ms,5m)) binned_timestamp,\n    \"SLAStatus\",\n    count  (distinct \"Contact Id\") \"SLAStatusCount\"\n\nFROM ContactQuery \nWHERE \n    COALESCE(\"Queue Name\",'<None>')  IN ($QueueName) \n\nGROUP BY BIN(time, greatest($__interval_ms,5m)),  \"SLAStatus\"\n),\n\nCountInBins AS (\nSELECT \n    binned_timestamp,\"SLAStatus\",\n    SUM (\"SLAStatusCount\") \"Number of Status Occurance\"\nFROM BaseBinning\nGROUP BY binned_timestamp,\"SLAStatus\"\n)\nSELECT \n    \"SLAStatus\",\n    CREATE_TIME_SERIES (binned_timestamp,\"Number of Status Occurance\") \"Num Of\"\nFROM CountInBins\nGROUP BY \"SLAStatus\"\nORDER BY \"SLAStatus\"",
     "table": "\"Table1\""
    }
   ]
  }
 ]
}